# Generated by Django 5.0.6 on 2024-06-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
                ('item_description', models.TextField()),
                ('price', models.FloatField()),
                ('date_added', models.DateField()),
            ],
        ),
    ]
