# Generated by Django 5.0.6 on 2024-06-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='suppliers',
            field=models.ManyToManyField(to='core.suppliers'),
        ),
    ]
